#!/usr/bin/env python3
"""
Extract the Osirus (gearmulator) editor's exact control coordinates per page and
map each to this module's g_params key, for the VST-layout arranger.

Join: skin parameterAttachment.parameter (name) -> parameterdescriptions
(name -> page 112=A/113=B, index) -> g_params (page,cc) -> key.

Emits:  var LAYOUT = { osc:{w,h,items:[{key,x,y,w,h,t}]}, lfo:{...}, ... };
(coords normalised per page to a tight bounding box; t = knob|select|toggle)
"""
import re, json, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKIN = ROOT / "libs/gearmulator/source/osirusJucePlugin/skins/Trancy/VirusC_Trancy.json"
PDSC = ROOT / "libs/gearmulator/source/osirusJucePlugin/parameterDescriptions_C.json"
CPP  = ROOT / "src/dsp/virus_plugin.cpp"

def strip_line_comments(t):
    out, i, n, instr, esc = [], 0, len(t), False, False
    while i < n:
        c = t[i]
        if instr:
            out.append(c)
            if esc: esc = False
            elif c == '\\': esc = True
            elif c == '"': instr = False
        elif c == '"': instr = True; out.append(c)
        elif c == '/' and i+1 < n and t[i+1] == '/':
            while i < n and t[i] != '\n': i += 1
            continue
        else: out.append(c)
        i += 1
    return ''.join(out)

def loose_json(p):
    t = strip_line_comments(p.read_text())
    t = re.sub(r',(\s*[}\]])', r'\1', t)
    return json.loads(t, strict=False)

# name -> (page01, index)
name2pi = {}
for p in loose_json(PDSC)["parameterdescriptions"]:
    pg = p.get("page")
    if pg == 112: name2pi[p["name"]] = (0, p["index"])
    elif pg == 113: name2pi[p["name"]] = (1, p["index"])

# (page,cc) -> key
cpp = CPP.read_text()
arr = re.search(r'static\s+const\s+virus_param_t\s+g_params\s*\[\]\s*=\s*\{(.*?)\n\};', cpp, re.S).group(1)
PAGE = {"VIRUS_PAGE_A": 0, "VIRUS_PAGE_B": 1}
pc2key = {}
for m in re.finditer(r'\{\s*"([^"]+)"\s*,\s*"[^"]*"\s*,\s*(VIRUS_PAGE_[AB])\s*,\s*(\d+)\s*,', arr):
    pc2key[(PAGE[m.group(2)], int(m.group(3)))] = m.group(1)

skin = loose_json(SKIN)

def find_pages(node, out):
    if isinstance(node, dict):
        if node.get("name") in ("page_osc", "page_lfo", "page_fx", "page_arp"):
            out[node["name"]] = node
        for v in node.values(): find_pages(v, out)
    elif isinstance(node, list):
        for v in node: find_pages(v, out)

pages = {}
find_pages(skin, pages)

def collect(node, items):
    if isinstance(node, dict):
        pa = node.get("parameterAttachment")
        if pa and "parameter" in pa:
            if "rotary" in node and "spritesheet" in node: g, t = node["spritesheet"], "knob"
            elif "combobox" in node: g, t = node["combobox"], "select"
            elif "button" in node: g, t = node["button"], "toggle"
            else: g = None
            if g and all(k in g for k in ("x", "y", "width", "height")):
                items.append((pa["parameter"], float(g["x"]), float(g["y"]),
                              float(g["width"]), float(g["height"]), t))
        for k, v in node.items():
            if k != "parameterAttachment": collect(v, items)
    elif isinstance(node, list):
        for v in node: collect(v, items)

LAYOUT, stats = {}, {}
for pid, key in (("page_osc","osc"),("page_lfo","lfo"),("page_fx","fx"),("page_arp","arp")):
    raw = []
    if pid in pages: collect(pages[pid], raw)
    seen, items = set(), []
    for name, x, y, w, h, t in raw:
        k = pc2key.get(name2pi.get(name)) if name2pi.get(name) else None
        if not k or k in seen: continue
        seen.add(k)
        items.append({"key": k, "x": x, "y": y, "w": w, "h": h, "t": t})
    PAD_T, PAD = 26, 10
    minx = min(i["x"] for i in items); miny = min(i["y"] for i in items)
    maxx = max(i["x"]+i["w"] for i in items); maxy = max(i["y"]+i["h"] for i in items)
    for i in items:
        i["x"] = round(i["x"]-minx+PAD, 1); i["y"] = round(i["y"]-miny+PAD_T, 1)
        i["w"] = round(i["w"], 1); i["h"] = round(i["h"], 1)
    LAYOUT[key] = {"w": round(maxx-minx+2*PAD, 1), "h": round(maxy-miny+PAD_T+PAD, 1), "items": items}
    stats[key] = len(items)

sys.stderr.write("VST layout: " + ", ".join("%s=%d" % (k, v) for k, v in stats.items()) + "\n")
print("/* AUTO-GENERATED by scripts/gen_vst_layout.py from the Osirus Trancy skin. */")
print("var LAYOUT = " + json.dumps(LAYOUT, ensure_ascii=False, separators=(",", ":")) + ";")
