#!/usr/bin/env python3
"""
Extract the Virus parameter model from src/dsp/virus_plugin.cpp so the Remote UI
(web_ui.html) speaks the exact same keys / ranges / enum labels as the DSP.

Emits a JS snippet to stdout:
    var OPTS = { opts_xxx: ["a","b",...], ... };
    var PARAMS = { key: {name, page, cc, min, max, model, opts}, ... };
    var PARAM_ORDER = [ "key", ... ];   // g_params declaration order

page: 0 = Page A (standard CC), 1 = Page B (polypressure/SysEx)
model: 0 = ALL (Virus A+), 1 = BC (Virus B/C only), 2 = C (Virus C only)
opts: name of an OPTS array, or null for a plain numeric param.
"""
import re, sys, json, pathlib

SRC = pathlib.Path(__file__).resolve().parent.parent / "src" / "dsp" / "virus_plugin.cpp"
text = SRC.read_text()

# ---- enum option arrays: static const char *opts_xxx[] = { "a", "b", ... };
opts = {}
for m in re.finditer(r'static\s+const\s+char\s*\*\s*(opts_\w+)\s*\[\]\s*=\s*\{(.*?)\};', text, re.S):
    name, body = m.group(1), m.group(2)
    labels = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
    opts[name] = labels

# ---- g_params rows. Grab only the g_params[] array body.
arr = re.search(r'static\s+const\s+virus_param_t\s+g_params\s*\[\]\s*=\s*\{(.*?)\n\};', text, re.S)
if not arr:
    sys.exit("could not locate g_params[]")
body = arr.group(1)

PAGE = {"VIRUS_PAGE_A": 0, "VIRUS_PAGE_B": 1}
MODEL = {"VIRUS_MODEL_ALL": 0, "VIRUS_MODEL_BC": 1, "VIRUS_MODEL_C": 2}

params = {}
order = []
# {"key", "Name", VIRUS_PAGE_A, 17, 0, 127, VIRUS_MODEL_ALL, OPTS(opts_x) | NO_OPTS},
row_re = re.compile(
    r'\{\s*"([^"]+)"\s*,\s*"([^"]*)"\s*,\s*'
    r'(VIRUS_PAGE_[AB])\s*,\s*(\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*'
    r'(VIRUS_MODEL_\w+)\s*,\s*'
    r'(?:OPTS\((opts_\w+)\)|NO_OPTS)\s*\}'
)
for m in row_re.finditer(body):
    key, name, page, cc, mn, mx, model, optname = m.groups()
    params[key] = {
        "name": name,
        "page": PAGE[page],
        "cc": int(cc),
        "min": int(mn),
        "max": int(mx),
        "model": MODEL[model],
        "opts": optname if optname else None,
    }
    order.append(key)

# Only emit the opts arrays actually referenced, to keep the bundle lean.
used = {p["opts"] for p in params.values() if p["opts"]}
opts = {k: v for k, v in opts.items() if k in used}

# ---- bipolar flag: cross-reference upstream parameterDescriptions_C.json.
# Params whose toText formatter is "signed"/"pan"/"negPos" display as a value
# centered on 64 (raw 0-127, 64 = 0), so the knob shows a +/- value and fills
# from center. Page 112 = Page A, 113 = Page B; index == our cc.
bipolar = {}
DESC = (pathlib.Path(__file__).resolve().parent.parent /
        "libs/gearmulator/source/osirusJucePlugin/parameterDescriptions_C.json")
if DESC.exists():
    raw = DESC.read_text()
    raw = re.sub(r'//[^\n]*', '', raw)
    raw = re.sub(r'/\*.*?\*/', '', raw, flags=re.S)
    raw = re.sub(r',(\s*[}\]])', r'\1', raw)
    tt = {(d["page"], d["index"]): (d.get("toText") or "")
          for d in json.loads(raw)["parameterdescriptions"]}
    for key, p in params.items():
        if p["opts"]:
            continue  # enums/toggles are never bipolar knobs
        page = 112 if p["page"] == 0 else 113
        if tt.get((page, p["cc"])) in ("signed", "pan", "negPos"):
            bipolar[key] = 1
    sys.stderr.write("bipolar=%d\n" % len(bipolar))
else:
    sys.stderr.write("WARN: %s not found; BIPOLAR empty\n" % DESC)

out = []
out.append("/* AUTO-GENERATED by scripts/gen_web_ui_params.py from virus_plugin.cpp. */")
out.append("/* Do not edit by hand — re-run the generator if g_params changes.       */")
out.append("var OPTS = " + json.dumps(opts, ensure_ascii=False) + ";")
out.append("var PARAMS = " + json.dumps(params, ensure_ascii=False) + ";")
out.append("var PARAM_ORDER = " + json.dumps(order, ensure_ascii=False) + ";")
out.append("var BIPOLAR = " + json.dumps(bipolar, ensure_ascii=False) + ";")
sys.stderr.write("params=%d opts=%d\n" % (len(params), len(opts)))
print("\n".join(out))
